name: "direct_planner"
description: "Natural-Planner evaluation for non reasoning models"

model:
  max_tokens: 512           
  max_model_len: 8192
  temperature: 0.0          
  top_p: 0.9
  stop_sequences: ["<|im_end|>", "<|endoftext|>", "</s>"]
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9

evaluation:
  num_questions: null
  start_question: null
  end_question: null
  batch_size: 1
  compute_metrics: true

prompting:
  system_prompt: "You must limit your answer to exactly {max_tokens} tokens or fewer."
  user_template: "{prompt}"

output:
  save_detailed_responses: true
  save_timing_metrics: true
  save_energy_metrics: true
  save_budget_analysis: true