name: "np_trip"
description: "Natural-Plan Trip-Planning evaluation (1600 examples)"

model:
  max_tokens: 2048
  max_model_len: 5000
  temperature: 0.0  
  top_p: 0.9
  stop_sequences: ["<|im_end|>", "<|endoftext|>", "</s>"]
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9

evaluation:
  num_questions: null   
  batch_size: 1
  compute_metrics: true 

prompting:
  system_prompt: "You are an expert trip planner. Provide the best plan in no more than 512 tokens."
  user_template: "{prompt}\n\nPlease answer in at most 512 tokens."

output:
  save_detailed_responses: true
  save_timing_metrics: true
  save_energy_metrics: true 